### ISSUE TITLE
Tools für KeyGen und Packen mit Keys

### ISSUE THREAD

**Issue by senshi-x** [OperationPandoraTrigger/OPT-Tools#2]
armake2 keygen in nettes Tool verpacken

Packen von Mod (Clientmod) in Zukunft mit Signatur by default.
Bitte mit optionalem Flag, um ohne Sig bauen zu können.

Servermod braucht es nicht (weil eh nur Server), und Missionen gehen nicht.

**Comment by formtapez** [comment]
Done in https://github.com/OperationPandoraTrigger/OPT-Tools/pull/1
Optionales Flag weggelassen - Wenn es keine Keys gibt, werden vorher eben neue erstellt.

**Comment by senshi-x** [comment]
Solange es nicht zur Key-Schwemme führt, ist es mir recht, ja :) . Keys müssen ja dann auch jedesmal richtig in A3\keys platziert/ersetzt werden, und die .bisig mit.
