### ISSUE TITLE
Dev-Flag manuell setzbar machen

### ISSUE THREAD

**Issue by senshi-x** [OperationPandoraTrigger/OPT-Tools#3]
Die metadata.bat sollte es noch ermöglichen, das Dev-Flag für CLib und OPT separat an- oder auszuschalten.

Gerade CLib im Dev-Modus produziert einen immensen Log- und systemchat-Spam. Kann hilfreich sein, aber nur bei dedizierter Bug- oder Eventjgad. Sollte by default also 'release' sein.

**Comment by formtapez** [comment]
in #4 umgesetzt
